import { HomeGoToSectionButton, NavBarLink } from "@/components/buttons";
import { LearningPath, NavBar } from "@/components/layout";
import { HomeSection, HomeSectionsContainer } from "@/components/sections";
import clsx from "clsx";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const isScrollSnappingEnabled = false;

  return (
    <>
      <Head>
        <title>About the Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={clsx(
          isScrollSnappingEnabled && "snap-mandatory snap-y",
          "h-screen overflow-y-auto bg-neutral-600"
        )}
      >
        <HomeSectionsContainer>
          <HomeSection
            number={0}
            className="min-h-screen snap-center flex flex-col relative"
          >
            <NavBar />

            <Image
              className="object-cover block absolute inset-0 w-full h-full"
              src="/sections/welcome/background.png"
              height={1280}
              width={720}
              aria-hidden
              alt=""
            />

            <div className="relative z-10 flex flex-row flex-1 p-6">
              <div className="flex flex-1 flex-col items-center justify-center">
                <header className="max-w-[24.5rem] space-y-6">
                  <h1 className="text-4xl text-neutral-dark-700">
                    You are probably wondering, <b>What is a rainforest?</b>
                  </h1>

                  <HomeGoToSectionButton />
                </header>
              </div>

              <aside className="w-[289px]">
                <LearningPath />
              </aside>
            </div>
          </HomeSection>

          <HomeSection
            number={1}
            className="h-screen snap-center flex bg-complementary-600 relative"
          >
            <div className="z-10">
              <HomeGoToSectionButton />
            </div>
          </HomeSection>

          <HomeSection
            number={2}
            className="h-screen snap-center bg-error-700 flex relative"
          >
            <div className="z-10">
              <HomeGoToSectionButton />
            </div>
          </HomeSection>
        </HomeSectionsContainer>
      </main>
    </>
  );
}
